### PR TITLE
Feature/29 fix restart loop

### LINKED ISSUE #29: Fix restart loop
When upgrading from ldap 2.4.48-3 to 2.4.58-3 and later to 2.6.2-1, ldap will never get healthy anymore.

### PR DESCRIPTION
**Pull request by sklein94**
Resolve #29

### CODE REVIEW

File: resources/srv/openldap/conf.d/ldap.conf.tpl [hunk 1]
```diff
@@ -2,11 +2,11 @@
 # LDAP Defaults
 #
 
-# See ldap.conf(5) for details
+# See ldap.conf(5) for detailse
```
Comment (JBartscher) [inline resources/srv/openldap/conf.d/ldap.conf.tpl:5]: Typo

File: file [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+  "EnvironmentVariables": null,
+  "Dependencies": [
+    {
+      "type": "dogu",
+      "name": "postfix",
+      "version": ""
+    }
+  ],
+  "OptionalDependencies": null
+}
```
Comment (JBartscher) [inline file:210]: Development artifact?
